### ISSUE TITLE
macOS High Sierra boot commands

### ISSUE THREAD

**Issue by Brantone** [mcandre/packer-templates#191]
Not sure if screens changed for High Sierra , or install is detecting different settings, but the boot commands for vmware-iso in `macos.json` start having issues around https://github.com/mcandre/packer-templates/blob/master/macos/macos.json#L1233
It gets confused at the screen for transferring from existing or previous mac (ex: where there's option for using Time Machine) and will some times end up going back a few screens or open prompt for network share.
As such, never gets to the screen to provide username/password.
Still trying to figure out the correct sequence to get past the hurdle.

**Comment by mcandre** [comment]
Might as well start over with #232.
