### ISSUE TITLE
Is it possible to run MacOs inside virtualBox on Ubuntu ?

### ISSUE THREAD

**Issue by gedw99** [mcandre/packer-templates#253]
https://github.com/mcandre/packer-templates/tree/master/macos

It says you must have MacOS host. But i think thats a legal thing.
I am stuck on ubuntu and need to be able to build and sign stuff for MacOS, and so am hoping it will work on my Ubuntu machine. 
Also i am guessing that i have to have a Intel CPU and GPU ?

Any tips would be great as there seems to be a plethora on opinions on the internet tubes and its so hard to know what hardware to buy. I need to buy hardware because its just too slow on my crappy ubuntu laptop :) 

I can then use Mage to script up building and signing my app inside the virtual MacOS.

**Comment by gedw99** [comment]
BTW all this stuff you have done is really a life saver. Really appreciate you making this.

**Comment by mcandre** [comment]
Yes, running a mac VM officially requires mac hardware. You can install Ubuntu on mac hardware and then run a mac VM on top.
