### ISSUE TITLE
Separate macOS ISO generation into its own project

### ISSUE THREAD

**Issue by mcandre** [mcandre/packer-templates#78]
So that the ISO can be hosted online and reused without requiring regeneration;

So that a checksum file can be hosted alongside and presented to `iso_checksum_url` in packer (unfortunately, the ISO generation process results in an unstable checksum, so these files are best uploaded as a pair);

So that the user building a Vagrant base box with packer does not need to rely on a macOS host.

**Comment by bacongravy** [comment]
You might be interested in taking a look at [macinbox](https://github.com/bacongravy/macinbox), which provides a packer-free way to build a Vagrant base box of High Sierra, and avoids the need to disable SIP. If you combine that approach with [vagrant-package-vmware](https://github.com/bacongravy/vagrant-package-vmware) you can build a variety of boxes that build upon each other without using packer at all.

**Comment by mcandre** [comment]
https://github.com/mcandre/macos-isos
