### ISSUE TITLE
macOS: Accelerate packing

### ISSUE THREAD

**Issue by mcandre** [mcandre/packer-templates#88]
Speed up packing macOS boxes, by reducing the number of reboots, and by avoiding VoiceOver.

* [ ] Use terminal to disable SIP in nvram before macOS installation, removing the need for holding R and pressing Super to reboot into Recovery Mode.
* [ ] Use terminal to activate VoiceOver for initial macOS installation, removing the need for pressing Super F5 to activate VoiceOver.
* [ ] Repeatedly press the Up arrow key for 50 minutes during initial macOS installation, in order to prevent the guest from going to sleep, which loses focus on country selection. This removes the need for pressing Super F5 to activate VoiceOver.
* [ ] Reboot with normal mode to continue VMware tools installation.
* [ ] `launchctl load /System/Library/LaunchDaemons/ssh.plist` after editing, in order to skip rebooting to execute sshd.

**Comment by bacongravy** [comment]
Improvement [hashicorp/packer#5681](https://github.com/hashicorp/packer/pull/5681) was released in version 1.2.0 (February 9, 2018).

**Comment by mcandre** [comment]
Changing the nature of this ticket from avoiding formerly unmerged features, to simply accelerating packing time.

**Comment by mcandre** [comment]
Meh, the vast majority of the packing time for this guest is spent running the macOS installer (~1.5 hours), relatively few gains to be had by shaving off a couple seconds here and there.
